services:
  db:
    image: mysql:8
    container_name: movietrack-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: movietrack
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: movietrack-backend
    ports:
      - "3000:3000"
    depends_on:
      - db
    restart: always
    environment:
      - NODE_ENV=development

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: movietrack-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: always

volumes:
  db_data:
