services:
  backend:
    build: ./back-end
    container_name: movie_backend
    ports:
      - "3000:3000"
    env_file:
      - ./back-end/.env
    volumes:
      - ./back-end:/app
    depends_on:
      - db

  frontend:
    build: ./front-end
    container_name: movie_frontend
    ports:
      - "8080:8080"
    volumes:
      - ./front-end:/app
    depends_on:
      - backend

  db:
    image: mysql:8.0
    container_name: movie_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: movietrack
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
